#ifndef _KUIMSGDEF_H
#define _KUIMSGDEF_H

#define UI_NOTIFY_STR 5
#define UI_WARNING_STR 6
#define SAVE_DECK_OK_STR 7
#define DEL_DECK_NOTIFY_STR 8
#define NEED_HERO_CARD_STR 9
#define NEED_30_CARD_STR 10
#define END_CARDGROUP_LESSON_STR 11
#define WILL_BUY_STR 12
#define MONEY_LOW_STR 13
#define OPEN_CARDGROUP 14
#define OPEN_SHOP 15
#define OPEN_ADVENTURE 16
#define CHIP_NO_ENOUGH 17
#define NEW_DAILY_STAGE 18
#define ACTIVE_TOWER 19
#endif // __HELLOWORLD_SCENE_H__	
